// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb'];
    AButton: typeof import('ant-design-vue/es')['Button'];
    ACard: typeof import('ant-design-vue/es')['Card'];
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox'];
    ACol: typeof import('ant-design-vue/es')['Col'];
    ADivider: typeof import('ant-design-vue/es')['Divider'];
    ADropdown: typeof import('ant-design-vue/es')['Dropdown'];
    AForm: typeof import('ant-design-vue/es')['Form'];
    AFormItem: typeof import('ant-design-vue/es')['FormItem'];
    AInput: typeof import('ant-design-vue/es')['Input'];
    ALayout: typeof import('ant-design-vue/es')['Layout'];
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent'];
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader'];
    AMenu: typeof import('ant-design-vue/es')['Menu'];
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem'];
    ARow: typeof import('ant-design-vue/es')['Row'];
    Icon: typeof import('./components/Icon/index.vue')['default'];
    Modal: typeof import('./components/Modal/index.vue')['default'];
    Table: typeof import('./components/Table/index.vue')['default'];
    TableFilter: typeof import('./components/TableFilter/index.vue')['default'];
    Upload: typeof import('./components/Upload/index.vue')['default'];
  }
}

export {};
