// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar'];
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb'];
    AButton: typeof import('ant-design-vue/es')['Button'];
    ACard: typeof import('ant-design-vue/es')['Card'];
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox'];
    ACol: typeof import('ant-design-vue/es')['Col'];
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker'];
    ADivider: typeof import('ant-design-vue/es')['Divider'];
    ADropdown: typeof import('ant-design-vue/es')['Dropdown'];
    AForm: typeof import('ant-design-vue/es')['Form'];
    AFormItem: typeof import('ant-design-vue/es')['FormItem'];
    AInput: typeof import('ant-design-vue/es')['Input'];
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch'];
    AMenu: typeof import('ant-design-vue/es')['Menu'];
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem'];
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm'];
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker'];
    AResult: typeof import('ant-design-vue/es')['Result'];
    ARow: typeof import('ant-design-vue/es')['Row'];
    ASelect: typeof import('ant-design-vue/es')['Select'];
    ASpace: typeof import('ant-design-vue/es')['Space'];
    ASpin: typeof import('ant-design-vue/es')['Spin'];
    ATable: typeof import('ant-design-vue/es')['Table'];
    ATabPane: typeof import('ant-design-vue/es')['TabPane'];
    ATabs: typeof import('ant-design-vue/es')['Tabs'];
    Icon: typeof import('./components/Icon/index.vue')['default'];
    Modal: typeof import('./components/Modal/index.vue')['default'];
    Table: typeof import('./components/Table/index.vue')['default'];
    TableFilter: typeof import('./components/TableFilter/index.vue')['default'];
    Upload: typeof import('./components/Upload/index.vue')['default'];
  }
}

export {};
